language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
  matrix:
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=flake8
  global:
    - CHAIN_SYNC_BLOCK_DELTA=100
    - SOLC_BINARY="$TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/solc"
cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/
    - $TRAVIS_BUILD_DIR/solc-versions/solidity-0.3.6/build/
    - $HOME/.ethash/
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
install:
  - ./bin/install_solc.sh
  - travis_retry sudo apt-get install -y ethereum
  - travis_retry pip install setuptools --upgrade
  - travis_retry pip install tox
before_script:
  - ls -lah $TRAVIS_BUILD_DIR/solc-versions/solc-0.3.6/
  - ./solc-versions/solc-0.3.6/solc --version
  - mkdir -p $HOME/.ethash
  - geth makedag 0 $HOME/.ethash
script:
  - tox -e $TOX_ENV --recreate
after_script:
  - cat .tox/$TOX_ENV/log/*.log

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: euri10
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: euri10/flask_web3
    condition: $TOXENV == py35
