language: python
python:
- '3.5'
dist: trusty
sudo: required
before_install:
- travis_retry sudo add-apt-repository -y ppa:ethereum/ethereum
- travis_retry sudo apt-get update
- travis_retry sudo apt-get install -y ethereum
- mkdir -p $HOME/.ethash
- geth makedag 0 $HOME/.ethash
env:
  matrix:
  - TOX_ENV=py35
  - TOX_ENV=flake8
cache:
  - pip: true
  - directories:
    - $HOME/.ethash
install:
- travis_retry pip install setuptools --upgrade
- travis_retry pip install tox
script:
- tox -e $TOX_ENV
after_script:
- cat .tox/$TOX_ENV/log/*.log
deploy:
  true:
    condition: $TOXENV == py35
    repo: euri10/flask_web3
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: MEGpUqYHTMTxU9/NShuiRJcZrizzEYxbdzvqdtB3+oNVp8pLTdm/OQW0mGQOY+3K3gE5y4ovXvRWoJDF+gF7Kr3BXemGPlkx/VHcWaoKVIbW845UvoR5SLrYqUkf5o/GiVt8+qI5XSTHEldS5K8k/KJL/OJ2yR9ktlNcp7bmRiqhe9iXI66zvA65iL6ivqqDtD3qxf1PKsD7zsydvinxPrknqFlZFzt2QhnaidOsKbziQPQVe8+j1xvHxofhfOeLthUyQkRfG7fkHt6g2yYpGuK9KVmCaVHXh0VNtyr8y9NL5CqO4pnxMiLqa4oetKpBX7jr+uT5ysnuUjQTdVGDxXo0u3nRkcIM4KIN5qF3NfV3NnRYMa6pc/+ZZvrD+xKb6YVhhBf2zec9uClz4ZFt+ToMVQnXyEjSVC4JmIN7RfYlhbxLm3IetIh8oVs+thU2CHoeRpngFtUUXPEb+n2dLEwofnv74IP5HK6a/UEpGcVzaZxoKHT1MEF86LCTRcQ2glp+GQsIe9Q02l1aJXrBYbFCUkwkXAQ8tBKiA3po4NdLMJjgT6bRNHhzl3GBkmInHxAQNVtcYFnCmx2EKLRKY6recEs45vmHgM9oj2kEm8Z99JcHHWECw3fO0aCW/QwO6lGaosspC4ft0ieH7H9uu+3UO7VHNeVGtoLTjGSetOs=
  provider: pypi
  user: euri10



